# =============================================================================
# ADAPTIQ PROJECT CONFIGURATION
# =============================================================================
# This file contains all the configuration settings for your AdaptiQ project.
# Please update the placeholder values with your actual project information.
# Reports folder: Contains summary content for both the default run and optimized run, including the final optimized prompt and a general overview.
# Results folder: Stores summary results for both runs, featuring the simulated optimized prompt and Q-table for each mode.
# Report_data folder: Holds updated JSON run results for local storage.

# --- Project Information ---
project_name: "your_project_name"        # Name of your project
email: ""          # Developer's email for contact and support

# --- LLM Configuration ---
# Currently only OpenAI is supported
llm_config:
  provider: "openai"                     # LLM provider (only 'openai' supported)
  model_name: "gpt-4o-mini"              # OpenAI model to use
  api_key: "your_openai_api_key"         # Your OpenAI API key

# --- Framework Adapter Configuration ---
# Currently only CrewAI is supported
framework_adapter:
  name: "crewai"                         # Framework name (only 'crewai' supported)
  settings:
    execution_mode: "prod"                # Execution mode (dev or prod)
    log_source:
      type: "file_path"                  # Type of log source
      path: "path/to/your/log.txt"       # Path to your agent's log file

# --- Agent Configuration Files ---
# Paths to your agent's configuration files
agent_modifiable_config:
  prompt_configuration_file_path: "path/to/your/config/tasks.yaml"    # Path to tasks configuration
  agent_definition_file_path: "path/to/your/config/agents.yaml"       # Path to agents configuration
  agent_name: "your_agent_name"                                       # Name of your agent
  agent_tools:
    - name: "ExampleTool"
      description: "What action that tool does"


# --- Report Output Configuration ---
# Where AdaptiQ will save optimization reports
report_config:
  output_path: "reports/your_project_name.md"    # Path for the optimization report

# --- Alert Mode Configuration ---
# Configure when AdaptiQ should generate reports
alert_mode:
  # On-demand mode: Generate report after specified number of runs
  on_demand:
    enabled: false                        # Enable on-demand reporting
    runs: 5                              # Number of runs before generating report

  # Per-run mode: Generate report after each run
  per_run:
    enabled: true                       # Enable per-run reporting

# =============================================================================
# NEXT STEPS:
# 1. Update all placeholder values with your actual project information
# 2. Validate your configuration: adaptiq wizard check config adaptiq_config.yml
# 3. Instrument your code with @instrumental_logger and @instrumental_run decorators
# 4. Run your first optimization: adaptiq wizard run pipeline
# =============================================================================
